---
#This root stack relies on the infrastructure stack already being created.
#The reason the infrastructure stack is created separately from the root stack is to do with global resources which should not be torn down (e.g. S3 buckets)
AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack.
Parameters:
  pCloudformationBucket:
      Description: Base URL for cloudformation templates 
      Type: String
      Default: https://s3-eu-west-2.amazonaws.com/jupyterhub-cloudformation-631013143897
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "/", [!Ref pCloudformationBucket,"vpc", "vpc-2azs.yml"] ]
      TimeoutInMinutes: "10"
  Hub:
    DependsOn: 
      - "VPC"
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NetworkStackName: !GetAtt VPC.Outputs.StackName
        KeyName: 'jupyterhub'
        VPCId: !GetAtt VPC.Outputs.VPC
      TemplateURL: !Join [ "/", [!Ref pCloudformationBucket,"jupyterhub", "hub.yml"] ]
      TimeoutInMinutes: "10"
  NATA:
    DependsOn: "VPC"
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        NetworkStackName: !GetAtt VPC.Outputs.StackName
        SubnetZone: 'A'
      TemplateURL: !Join [ "/", [!Ref pCloudformationBucket,"vpc", "nat.yml"] ]
      TimeoutInMinutes: "10"
  Users:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join [ "/", [!Ref pCloudformationBucket, "users.yml"] ]
      TimeoutInMinutes: "10"