---
#This root stack relies on the infrastructure stack already being created.
#The reason the infrastructure stack is created separately from the root stack is to do with global resources which should not be torn down (e.g. S3 buckets)
AWSTemplateFormatVersion: '2010-09-09'
Description: Root Stack.
Parameters:
  CloudformationBucketName:
      Description: Base URL for cloudformation templates 
      Type: String
  CloudformationBucket:
      Description: Base URL for cloudformation templates 
      Type: String
  SshKeyName: 
      Description: Name of SSH keypair used to connect to the Hub
      Type: String
  InboundIP:
      Description: IP from which to allow HTTP and SSH access
      Type: String
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ExportPrefix: !Ref "AWS::StackName"
      TemplateURL: !Join [ "/", [!Ref CloudformationBucket,"vpc", "vpc-2azs.yml"] ]
      TimeoutInMinutes: "10"
  NATA:
    DependsOn: "VPC"
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ExportPrefix: !Ref "AWS::StackName"
        SubnetZone: 'A'
      TemplateURL: !Join [ "/", [!Ref CloudformationBucket,"vpc", "nat.yml"] ]
      TimeoutInMinutes: "10"
  Users:
    DependsOn: "VPC"
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ExportPrefix: !Ref "AWS::StackName"
        MountTargetSecurityGroupId: !GetAtt VPC.Outputs.MountTargetSecurityGroupId
        ServerSubnetId: !GetAtt VPC.Outputs.SubnetAPrivate
      TemplateURL: !Join [ "/", [!Ref CloudformationBucket, "users.yml"] ]
      TimeoutInMinutes: "10"
  Hub:
    DependsOn: 
      - "VPC"
      - "Users"
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ExportPrefix: !Ref "AWS::StackName"
        KeyName: !Ref "SshKeyName"
        InboundIP: !Ref "InboundIP"
        CloudFormationBucket: !Ref CloudformationBucketName
        ServerKeyName: !Sub "${AWS::StackName}-ServerKey"
        ServerTemplateUrl: !Join [ "/", [!Ref CloudformationBucket,"jupyterhub", "server.yml"] ]
      TemplateURL: !Join [ "/", [!Ref CloudformationBucket,"jupyterhub", "hub.yml"] ]
      TimeoutInMinutes: "10"